### PR TITLE
Replace status icon

### PR DESCRIPTION
**Pull request by flschweiger**
This PR replaces the current icon with a flat 'color picker' icon so IMHO it fits better with the other system icons. Open for discussion 😃

### CODE REVIEW

**Comment by acheronfail** [comment]
Hmm, I agree that the magnifying glass might not _exactly_ portray the intent of the app, and that a colour dropper is a more universal symbol for this kind of thing.

When you say:

> IMHO it fits better with the other system icons.

Which icons are you referring to? 🤔

**Comment by acheronfail** [comment]
I did originally use the magnifying glass since that's what the application pops up on the screen - it "magnifies" parts of the screen and allows you to pick pixels.

With that in mind, what do you think about an icon like this?

mag_dropper

**Comment by flschweiger** [comment]
Yey! Thanks for merging the Flutter PR 😃 

With system icons I mean the icons in the top right of the screen:

image

They are all flat and plain white (no two-tone icons). I really like the new icon though. I just feel that it might have too much 'detail' for the small area on the top right. The lines should be a little thicker and maybe the complexity reduced.

Maybe something like this:

image

Let me know what you think!

I have attached the Affinity Design file for the small icon here (in case you want to use / modify it):
[icon.afdesign.zip](https://github.com/acheronfail/pixel-picker/files/2874247/icon.afdesign.zip)

**Comment by flschweiger** [comment]
FYI: Just pushed a new commit which would add the new version of the picker icon in case you want to use that one 😉

**Comment by flschweiger** [comment]
Closed because of #19

**Pull request closed without merging**
